### PR TITLE
Starterclasses

### PR DESCRIPTION
**Pull request by cstritzke**
Some new features here:
- I refactored the big ugly launcher class. We can now add starters for tools and controllers as separate classes. Each class needs to implement the method "getCommandLine()". Tools and controllers can be started synchronously or asynchronously. It also has to be referenced in the Starter Factory class.
- We no longer need to manually install and load bundles in the ODL karaf prompt. The ODL installer script does that automatically now.

### CODE REVIEW

**Comment by cstritzke** [comment]
One new feature I've forgotten before:
- Consoles are named appropriately now: "Ryu", "Ryu Shim", "ODL Shim", "Mininet", etc

**Comment by ElisaRojas** [comment]
@cstritzke : @andres-beato was just about to commit some material because he tested it and found some bugs... but you merged just before. How do we proceed? Do we restore the branch before?

**Comment by cstritzke** [comment]
Oh, I'm sorry for that.
I think it's easiest to rename the local branch, merge the new master branch, push it and create a new pull request. If renaming doesn't work, maybe you can just push the branch again.

**Comment by andres-beato** [comment]
@cstritzke, I've just restored the starter branch and then I've commited the changes.
You can merge now the branch with master :)

**Comment by cstritzke** [comment]
It worked :). Thanks a lot.

**Pull request merged**
